export const USER_POSTS_REQUEST = 'USER_POSTS_REQUEST'
export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS'
export const USER_POSTS_FAIL = 'USER_POSTS_FAIL'

export const USER_POST_COMMENT_REQUEST = 'USER_POST_COMMENT_REQUEST'
export const USER_POST_COMMENT_SUCCESS = 'USER_POST_COMMENT_SUCCESS'
export const USER_POST_COMMENT_FAIL = 'USER_POST_COMMENT_FAIL'

export const USER_CREATE_POST_REQUEST = 'USER_CREATE_POST_REQUEST'
export const USER_CREATE_POST_SUCCESS = 'USER_CREATE_POST_SUCCESS'
export const USER_CREATE_POST_FAIL = 'USER_CREATE_POST_FAIL'
export const USER_CREATE_POST_RESET = 'USER_CREATE_RESET'