export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'

export const USER_SEARCH_PROFILE_REQUEST = 'USER_SEARCH_PROFILE_REQUEST'
export const USER_SEARCH_PROFILE_SUCCESS = 'USER_SEARCH_PROFILE_SUCCESS'
export const USER_SEARCH_PROFILE_FAIL = 'USER_SEARCH_PROFILE_FAIL'

export const USERNAME_PROFILE_REQUEST = 'USERNAME_PROFILE_REQUEST'
export const USERNAME_PROFILE_SUCCESS = 'USERNAME_PROFILE_SUCCESS'
export const USERNAME_PROFILE_FAIL = 'USERNAME_PROFILE_FAIL'

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST'
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS'
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL'